webScraping
    old
    Projeto
        Controle
            Engine
                DataInput
                    __init__.py
                    Estrutura.py
                ProcessosExternos
                    Downloads
                        Pdf
                        __init__.py
                    __init__.py
                Web
                    Condicionais
                    Driver
                    __init__.py
                __init__.py
            __init__.py
            ProcessosInternos
                Arquivo
                    __init__.py
                Escrita
                    __init__.py
                Imagem
                    __init__.py
            Os
                __init__.py
            __init__.py
    ImagePdf
    Modelo
    Banco
    __init__.py
    Modelo.py
    PdfDownload
    BachareladoemAgronomia.pdf
    BachareladoemCienciadaComputacao.pdf
    BachareladoemQuimicaIndustrial.pdf
    BachareladoemZootecnia.pdf
    LicenciaturaemPedagogia.pdf
    LicenciaturaemQuimica.pdf
    TecnologiaemAlimentos.pdf
    TecnologiaemSistemasparaInternet.pdf